USE AutoRepairShop;

DROP TABLE IF EXISTS Service;
DROP TABLE IF EXISTS RepairOrder;
DROP TABLE IF EXISTS Vehicle;
DROP TABLE IF EXISTS Employee;
DROP TABLE IF EXISTS ServiceType;
DROP TABLE IF EXISTS Customer;
DROP TABLE IF EXISTS EmployeeType;

DROP PROCEDURE IF EXISTS PopulateEmployeeType;

DROP VIEW IF EXISTS ServiceView;
